name: Model Conversion Pipeline

on:
  push:
    branches:
      - main
      # - model-covert      # Change if your branch name is different

  workflow_dispatch:
    inputs:
      build_engine:
        description: "Build TensorRT Engine?"
        required: true
        default: "false"
        type: choice
        options:
          - "false"
          - "true"

jobs:
  convert-to-onnx:
    name: Convert PyTorch to ONNX
    if: github.event_name == 'push'
    runs-on: [self-hosted, Linux]

    defaults:
      run:
        working-directory: pytorch_to_tensorrt

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 1

      - name: Download LFS Files
        run: |
          git lfs pull

      - name: Verify Model File
        run: |
          git lfs ls-files
          ls -lh model.pth
          file model.pth

      - name: Check Python Version
        run: python3 --version

      - name: Install Dependencies
        run: |
          python3 -m pip install --break-system-packages --upgrade pip
          python3 -m pip install --break-system-packages -r requirements.txt

      - name: Convert PyTorch to ONNX
        run: |
          python3 convert-torch-to-onnx.py

      - name: Upload ONNX Model
        uses: actions/upload-artifact@v4
        with:
          name: model-onnx
          path: |
            pytorch_to_tensorrt/model.onnx
            pytorch_to_tensorrt/model.onnx.data

  convert-to-engine:
    name: Convert ONNX to TensorRT
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.build_engine == 'true'

    runs-on: [self-hosted, Linux]

    defaults:
      run:
        working-directory: pytorch_to_tensorrt

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 1

      - name: Download LFS Files
        run: |
          git lfs pull

      - name: Verify Model File
        run: |
          git lfs ls-files
          ls -lh model.pth
          file model.pth

      - name: Download ONNX Model from latest push run
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: test.yml   
          workflow_conclusion: success
          branch: main                     
          name: model-onnx
          path: pytorch_to_tensorrt

      - name: Verify Files
        run: |
          ls -lh
          test -f model.onnx
          test -f model.onnx.data

      - name: Convert ONNX to TensorRT Engine
        run: |
          python3 convert-onnx-to-tensorrt.py

      - name: Upload TensorRT Engine
        uses: actions/upload-artifact@v4
        with:
          name: model-engine
          path: pytorch_to_tensorrt/model.engine